
# This file is automatically generated, you probably don't want to edit this

askllmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            run = FALSE, ...) {

            super$initialize(
                package="askLLM",
                name="askllm",
                requiresData=TRUE,
                ...)

            private$..run <- jmvcore::OptionBool$new(
                "run",
                run,
                default=FALSE)

            self$.addOption(private$..run)
        }),
    active = list(
        run = function() private$..run$value),
    private = list(
        ..run = NA)
)

askllmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ask LLM about your data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Smoke test output"))}))

askllmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "askLLM",
                name = "askllm",
                version = c(1,0,0),
                options = options,
                results = askllmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Ask LLM about your data
#'
#' 
#' @param data .
#' @param run .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
askllm <- function(
    data,
    run = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("askllm requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- askllmOptions$new(
        run = run)

    analysis <- askllmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

