
# This file is automatically generated, you probably don't want to edit this

askllmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            question = "",
            includeSummary = TRUE,
            includeCatalog = TRUE,
            submit = FALSE,
            enableActions = FALSE,
            testConnection = FALSE,
            provider = "nim",
            model = "meta/llama-3.1-8b-instruct",
            baseUrl = "",
            maxLevels = 10,
            role = "consultant",
            promptLang = "en",
            systemPrompt = "",
            systemPromptVar = NULL, ...) {

            super$initialize(
                package="askLLM",
                name="askllm",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..question <- jmvcore::OptionString$new(
                "question",
                question,
                default="")
            private$..includeSummary <- jmvcore::OptionBool$new(
                "includeSummary",
                includeSummary,
                default=TRUE)
            private$..includeCatalog <- jmvcore::OptionBool$new(
                "includeCatalog",
                includeCatalog,
                default=TRUE)
            private$..submit <- jmvcore::OptionBool$new(
                "submit",
                submit,
                default=FALSE)
            private$..enableActions <- jmvcore::OptionBool$new(
                "enableActions",
                enableActions,
                default=FALSE)
            private$..llmColumns <- jmvcore::OptionOutput$new(
                "llmColumns")
            private$..testConnection <- jmvcore::OptionBool$new(
                "testConnection",
                testConnection,
                default=FALSE)
            private$..provider <- jmvcore::OptionList$new(
                "provider",
                provider,
                options=list(
                    "nim",
                    "gemini",
                    "openrouter",
                    "github",
                    "ollama",
                    "custom"),
                default="nim")
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="meta/llama-3.1-8b-instruct")
            private$..baseUrl <- jmvcore::OptionString$new(
                "baseUrl",
                baseUrl,
                default="")
            private$..maxLevels <- jmvcore::OptionInteger$new(
                "maxLevels",
                maxLevels,
                default=10,
                min=3,
                max=50)
            private$..role <- jmvcore::OptionList$new(
                "role",
                role,
                options=list(
                    "consultant",
                    "tutor",
                    "explainer"),
                default="consultant")
            private$..promptLang <- jmvcore::OptionList$new(
                "promptLang",
                promptLang,
                options=list(
                    "en",
                    "zh"),
                default="en")
            private$..systemPrompt <- jmvcore::OptionString$new(
                "systemPrompt",
                systemPrompt,
                default="")
            private$..systemPromptVar <- jmvcore::OptionVariable$new(
                "systemPromptVar",
                systemPromptVar,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)

            self$.addOption(private$..vars)
            self$.addOption(private$..question)
            self$.addOption(private$..includeSummary)
            self$.addOption(private$..includeCatalog)
            self$.addOption(private$..submit)
            self$.addOption(private$..enableActions)
            self$.addOption(private$..llmColumns)
            self$.addOption(private$..testConnection)
            self$.addOption(private$..provider)
            self$.addOption(private$..model)
            self$.addOption(private$..baseUrl)
            self$.addOption(private$..maxLevels)
            self$.addOption(private$..role)
            self$.addOption(private$..promptLang)
            self$.addOption(private$..systemPrompt)
            self$.addOption(private$..systemPromptVar)
        }),
    active = list(
        vars = function() private$..vars$value,
        question = function() private$..question$value,
        includeSummary = function() private$..includeSummary$value,
        includeCatalog = function() private$..includeCatalog$value,
        submit = function() private$..submit$value,
        enableActions = function() private$..enableActions$value,
        llmColumns = function() private$..llmColumns$value,
        testConnection = function() private$..testConnection$value,
        provider = function() private$..provider$value,
        model = function() private$..model$value,
        baseUrl = function() private$..baseUrl$value,
        maxLevels = function() private$..maxLevels$value,
        role = function() private$..role$value,
        promptLang = function() private$..promptLang$value,
        systemPrompt = function() private$..systemPrompt$value,
        systemPromptVar = function() private$..systemPromptVar$value),
    private = list(
        ..vars = NA,
        ..question = NA,
        ..includeSummary = NA,
        ..includeCatalog = NA,
        ..submit = NA,
        ..enableActions = NA,
        ..llmColumns = NA,
        ..testConnection = NA,
        ..provider = NA,
        ..model = NA,
        ..baseUrl = NA,
        ..maxLevels = NA,
        ..role = NA,
        ..promptLang = NA,
        ..systemPrompt = NA,
        ..systemPromptVar = NA)
)

askllmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        answer = function() private$.items[["answer"]],
        jmvResults = function() private$.items[["jmvResults"]],
        actionNote = function() private$.items[["actionNote"]],
        plan = function() private$.items[["plan"]],
        llmColumns = function() private$.items[["llmColumns"]],
        meta = function() private$.items[["meta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Ask LLM about your data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title="Instructions",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="answer",
                title="Response",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="jmvResults",
                title="Analyses run",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="actionNote",
                title="What the assistant did",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="plan",
                title="Action plan (audit)",
                clearWith=list()))
            self$add(jmvcore::Output$new(
                options=options,
                name="llmColumns",
                title="",
                initInRun=TRUE,
                measureType="continuous",
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="meta",
                title="",
                clearWith=list()))}))

askllmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "askLLM",
                name = "askllm",
                version = c(1,2,0),
                options = options,
                results = askllmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' jamovi Module Guider
#'
#' 
#' @param data .
#' @param vars .
#' @param question .
#' @param includeSummary .
#' @param includeCatalog .
#' @param submit .
#' @param enableActions .
#' @param testConnection .
#' @param provider .
#' @param model .
#' @param baseUrl .
#' @param maxLevels .
#' @param role .
#' @param promptLang .
#' @param systemPrompt .
#' @param systemPromptVar .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$answer} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$jmvResults} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$actionNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plan} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$llmColumns} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$meta} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
askllm <- function(
    data,
    vars,
    question = "",
    includeSummary = TRUE,
    includeCatalog = TRUE,
    submit = FALSE,
    enableActions = FALSE,
    testConnection = FALSE,
    provider = "nim",
    model = "meta/llama-3.1-8b-instruct",
    baseUrl = "",
    maxLevels = 10,
    role = "consultant",
    promptLang = "en",
    systemPrompt = "",
    systemPromptVar = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("askllm requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(systemPromptVar)) systemPromptVar <- jmvcore::resolveQuo(jmvcore::enquo(systemPromptVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(systemPromptVar), systemPromptVar, NULL))


    options <- askllmOptions$new(
        vars = vars,
        question = question,
        includeSummary = includeSummary,
        includeCatalog = includeCatalog,
        submit = submit,
        enableActions = enableActions,
        testConnection = testConnection,
        provider = provider,
        model = model,
        baseUrl = baseUrl,
        maxLevels = maxLevels,
        role = role,
        promptLang = promptLang,
        systemPrompt = systemPrompt,
        systemPromptVar = systemPromptVar)

    analysis <- askllmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

