
# This file is automatically generated, you probably don't want to edit this

askllmrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            question = "",
            includeSummary = TRUE,
            submit = FALSE,
            testConnection = FALSE,
            provider = "nim",
            model = "meta/llama-3.1-8b-instruct",
            baseUrl = "",
            role = "consultant",
            promptLang = "en",
            systemPrompt = "",
            systemPromptVar = NULL, ...) {

            super$initialize(
                package="askLLM",
                name="askllmr",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..question <- jmvcore::OptionString$new(
                "question",
                question,
                default="")
            private$..includeSummary <- jmvcore::OptionBool$new(
                "includeSummary",
                includeSummary,
                default=TRUE)
            private$..submit <- jmvcore::OptionBool$new(
                "submit",
                submit,
                default=FALSE)
            private$..testConnection <- jmvcore::OptionBool$new(
                "testConnection",
                testConnection,
                default=FALSE)
            private$..provider <- jmvcore::OptionList$new(
                "provider",
                provider,
                options=list(
                    "nim",
                    "gemini",
                    "openrouter",
                    "github",
                    "ollama",
                    "custom"),
                default="nim")
            private$..model <- jmvcore::OptionString$new(
                "model",
                model,
                default="meta/llama-3.1-8b-instruct")
            private$..baseUrl <- jmvcore::OptionString$new(
                "baseUrl",
                baseUrl,
                default="")
            private$..role <- jmvcore::OptionList$new(
                "role",
                role,
                options=list(
                    "consultant",
                    "tutor",
                    "explainer"),
                default="consultant")
            private$..promptLang <- jmvcore::OptionList$new(
                "promptLang",
                promptLang,
                options=list(
                    "en",
                    "zh"),
                default="en")
            private$..systemPrompt <- jmvcore::OptionString$new(
                "systemPrompt",
                systemPrompt,
                default="")
            private$..systemPromptVar <- jmvcore::OptionVariable$new(
                "systemPromptVar",
                systemPromptVar,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"),
                default=NULL)

            self$.addOption(private$..vars)
            self$.addOption(private$..question)
            self$.addOption(private$..includeSummary)
            self$.addOption(private$..submit)
            self$.addOption(private$..testConnection)
            self$.addOption(private$..provider)
            self$.addOption(private$..model)
            self$.addOption(private$..baseUrl)
            self$.addOption(private$..role)
            self$.addOption(private$..promptLang)
            self$.addOption(private$..systemPrompt)
            self$.addOption(private$..systemPromptVar)
        }),
    active = list(
        vars = function() private$..vars$value,
        question = function() private$..question$value,
        includeSummary = function() private$..includeSummary$value,
        submit = function() private$..submit$value,
        testConnection = function() private$..testConnection$value,
        provider = function() private$..provider$value,
        model = function() private$..model$value,
        baseUrl = function() private$..baseUrl$value,
        role = function() private$..role$value,
        promptLang = function() private$..promptLang$value,
        systemPrompt = function() private$..systemPrompt$value,
        systemPromptVar = function() private$..systemPromptVar$value),
    private = list(
        ..vars = NA,
        ..question = NA,
        ..includeSummary = NA,
        ..submit = NA,
        ..testConnection = NA,
        ..provider = NA,
        ..model = NA,
        ..baseUrl = NA,
        ..role = NA,
        ..promptLang = NA,
        ..systemPrompt = NA,
        ..systemPromptVar = NA)
)

askllmrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmrResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        code = function() private$.items[["code"]],
        explanation = function() private$.items[["explanation"]],
        links = function() private$.items[["links"]],
        caveat = function() private$.items[["caveat"]],
        meta = function() private$.items[["meta"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="R code tutor")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="instructions",
                title="",
                visible=TRUE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="code",
                title="R code \u2014 paste into Rj Editor",
                visible=TRUE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="explanation",
                title="What this code does",
                visible=TRUE,
                clearWith=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="links",
                title="",
                visible=TRUE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="caveat",
                title="",
                visible=TRUE,
                clearWith=list()))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="meta",
                title="",
                visible=TRUE,
                clearWith=list()))}))

askllmrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "askllmrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "askLLM",
                name = "askllmr",
                version = c(1,2,0),
                options = options,
                results = askllmrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' R code tutor
#'
#' 
#' @param data .
#' @param vars .
#' @param question .
#' @param includeSummary .
#' @param submit .
#' @param testConnection .
#' @param provider .
#' @param model .
#' @param baseUrl .
#' @param role .
#' @param promptLang .
#' @param systemPrompt .
#' @param systemPromptVar .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$code} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$explanation} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$links} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$caveat} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$meta} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
askllmr <- function(
    data,
    vars,
    question = "",
    includeSummary = TRUE,
    submit = FALSE,
    testConnection = FALSE,
    provider = "nim",
    model = "meta/llama-3.1-8b-instruct",
    baseUrl = "",
    role = "consultant",
    promptLang = "en",
    systemPrompt = "",
    systemPromptVar = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("askllmr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(systemPromptVar)) systemPromptVar <- jmvcore::resolveQuo(jmvcore::enquo(systemPromptVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(systemPromptVar), systemPromptVar, NULL))


    options <- askllmrOptions$new(
        vars = vars,
        question = question,
        includeSummary = includeSummary,
        submit = submit,
        testConnection = testConnection,
        provider = provider,
        model = model,
        baseUrl = baseUrl,
        role = role,
        promptLang = promptLang,
        systemPrompt = systemPrompt,
        systemPromptVar = systemPromptVar)

    analysis <- askllmrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

